### ISSUE TITLE
Install fails in bash "wc" command

### ISSUE THREAD

**Issue by radokristof** [tiredofit/docker-osticket#33]
Hi!

I have tried several tags, 3.5.3, 3.5.2, etc.. all fails with this for me:
`2023-05-27.22:59:54 [ERROR] ** [php-fpm] Requested enabling openssl however it doesn't exist!
2023-05-27.22:59:55 [ERROR] ** [php-fpm] Requested enabling session however it doesn't exist!
wc: radokristof: No such file or directory
/etc/cont-init.d/30-osticket: line 14: [: : integer expression expected
sed: -e expression #1, char 22: unterminated `s' command`

**Comment by radokristof** [comment]
Dashboard loads, but I can't login. I suspect that the install did not continue, because I can't see any lines which are in the setup files like "Database setup is succesful"

**Comment by tiredofit** [comment]
`3.5.4` fixes something related to the CRON_INTERVAL and should remove that error regarding unterminated sed command.

**Comment by radokristof** [comment]
@tiredofit Thanks! That error is gone really.
However I think the install still not starts correctly for me:
`
2023-05-28.10:57:43 [ERROR] ** [php-fpm] Requested enabling openssl however it doesn't exist!
2023-05-28.10:57:44 [ERROR] ** [php-fpm] Requested enabling session however it doesn't exist!
wc: radokristof: No such file or directory
/etc/cont-init.d/30-osticket: line 15: [: : integer expression expected
2023-05-28.10:57:45 [WARN] ** [osticket] New OSTicket Installation Detected.
2023-05-28.10:57:46 [NOTICE] ** [osticket] Applying configuration file security
2023-05-28.10:57:46 [STARTING] ** [nginx] [1] Starting nginx 1.25.0
2023-05-28.10:57:46 [STARTING] ** [php-fpm] [1] Starting php-fpm 8.1.18
2023-05-28.10:57:46 [STARTING] ** [monitoring] [1] Starting Zabbix Agent (classic) 6.4.2
2023-05-28.10:57:47 [STARTING] ** [scheduling] [1] Starting cron
`

If I try to log in from the web interface, I get an exception, saying that the query can't complete (really, because the schemas are not created yet...):
`
Fatal error: Uncaught InconsistentModelException: Unable to prepare query: Table 'osticket.ost_email' doesn't exist SELECT A1.* FROM `ost_email`
`

I tried waiting a few mins, but it does not change anything, no new logs, nothing.

**Comment by Dekat** [comment]
@radokristof I fixed the issue you encounter and created the dedicated PR #34.
You can, like me, build your own image based on this branch if you don't want to wait :wink:

**Comment by tiredofit** [comment]
Fixed in `3.5.5` thanks for the help @Dekat

**Comment by radokristof** [comment]
Thank you @Dekat!
@tiredofit after re-installing with the new image, it seems that setup can finish correctly.

However I still can't log-in with my admin credentials.
